Update eks-deployment-dev.yml

diff --git a/.github/workflows/eks-deployment-dev.yml b/.github/workflows/eks-deployment-dev.yml
--- a/.github/workflows/eks-deployment-dev.yml
+++ b/.github/workflows/eks-deployment-dev.yml
@@ -42,42 +42,42 @@ jobs:
       - name: Terraform Init
         run: |
           cd Terraform
-          if [ "${{ github.event.inputs.environment  }}" = "dev" ]; then
-          cd dev
-          terraform init -reconfigure -backend-config="bucket=${{ secrets.TERRAFORM_DEV_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"
-          elif [ "${{ github.event.inputs.environment  }}" = "prod" ]; then
-            cd prod
-            terraform init -reconfigure -backend-config="bucket=${{ secrets.TERRAFORM_PROD_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"
-          elif [ "${{ github.event.inputs.environment  }}" = "sandbox" ]; then
-            cd sandbox
+          # if [ "${{ github.event.inputs.environment  }}" = "dev" ]; then
+          # cd dev
+          # terraform init -reconfigure -backend-config="bucket=${{ secrets.TERRAFORM_DEV_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"
+          # elif [ "${{ github.event.inputs.environment  }}" = "prod" ]; then
+          #   cd prod
+          #   terraform init -reconfigure -backend-config="bucket=${{ secrets.TERRAFORM_PROD_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"
+          # elif [ "${{ github.event.inputs.environment  }}" = "sandbox" ]; then
+          #   cd sandbox
             terraform init -reconfigure -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"
-          fi
+          # fi
   
       - name: Terraform Plan
         run: |
           cd Terraform
-            if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
-          cd dev
-            elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
-          cd prod
-            elif [ "${{ github.event.inputs.environment }}" = "sandbox" ]; then
-          cd sandbox
-            else
-            echo "Invalid environment: ${{ github.event.inputs.environment }}"
-            exit 1
-          fi
+          #   if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
+          # cd dev
+          #   elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
+          # cd prod
+          #   elif [ "${{ github.event.inputs.environment }}" = "sandbox" ]; then
+          # cd sandbox
+          #   else
+          #   echo "Invalid environment: ${{ github.event.inputs.environment }}"
+          #   exit 1
+          # fi
           terraform plan -out=tfplan
       - name: Terraform Apply
         run: |
           cd Terraform
-            if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
-          cd dev
-            elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
-          cd prod
-            elif [ "${{ github.event.inputs.environment }}" = "sandbox" ]; then
-          cd sandbox
-            else
-            echo "Invalid environment: ${{ github.event.inputs.environment }}"
-            exit 1
-          fi
+          #   if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
+          # cd dev
+          #   elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
+          # cd prod
+          #   elif [ "${{ github.event.inputs.environment }}" = "sandbox" ]; then
+          # cd sandbox
+          #   else
+          #   echo "Invalid environment: ${{ github.event.inputs.environment }}"
+          #   exit 1
+          # fi
           terraform apply -out=tfplan
