adding files

diff --git a/.github/workflows/eks-deployment-dev.yml b/.github/workflows/eks-deployment-dev.yml
--- a/.github/workflows/eks-deployment-dev.yml
+++ b/.github/workflows/eks-deployment-dev.yml
@@ -57,16 +57,17 @@ jobs:
       - name: Terraform Plan
         run: |
           cd Terraform
-          if [ "${{ github.event.inputs.environment  }}" = "dev" ]; then
-            cd dev
-            terraform plan -backend-config="bucket=${{ secrets.TERRAFORM_DEV_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"
-          elif [ "${{ github.event.inputs.environment  }}" = "prod" ]; then
-            cd prod
-            terraform plan -backend-config="bucket=${{ secrets.TERRAFORM_PROD_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"
-          elif [ "${{ github.event.inputs.environment  }}" = "sandbox" ]; then
-            cd sandbox
-            terraform plan -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"
+            if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
+          cd dev
+            elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
+          cd prod
+            elif [ "${{ github.event.inputs.environment }}" = "sandbox" ]; then
+          cd sandbox
+            else
+            echo "Invalid environment: ${{ github.event.inputs.environment }}"
+            exit 1
           fi
+          terraform plan -out=tfplan
 
       # - name: Terraform Apply
       #   run: |
